modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/MJRLegends/Space-Astronomy-Tweaks/issues"
[[mods]]
modId="spaceastronomytweaks"
version="1.0.0"
displayName="SpaceAstronomyTweaks"
displayURL="https://minecraft.curseforge.com/projects/space-astronomy-tweaks"
credits="MJRLegends for making the mod"
authors="MJRLegends"
description='''
Tweaks for the Space Astronomy Mod Pack Series
'''
[[dependencies.spaceastronomytweaks]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.spaceastronomytweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"