modLoader="javafml"
loaderVersion="[25,)"
displayURL="https://minecraft.curseforge.com/projects/space-astronomy-tweaks"
credits="MJRLegends for making the mod"
authors="MJRLegends"
[[mods]]
modId="spaceastronomytweaks"
version="1.0.0"
displayName="SpaceAstronomyTweaks"
description='''
'''
[[dependencies.spaceastronomytweaks]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.spaceastronomytweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"